# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5670c943e97b4c875b0868d2ba1b39d16f734d5849fdecadd44f1a6901937a94f20eb6e100e873734ae7f075c009bf3670606c2863888b29035f7a9627924880

test:
  secret_key_base: 940f1b60d7e40e0462b29a8037efb5be42c539deeff98016685cadac7b27398a552e3db88f8ecd8eb0dac59b83831de979a3266d8659c2d5b1299fb4ecc8a2f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
